name: immolink
description: "A new Flutter project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  go_router: ^14.7.2
  flutter_riverpod: ^2.4.9
  mongo_dart: ^0.10.4
  shared_preferences: ^2.5.1
  font_awesome_flutter: ^10.8.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3

flutter:
  uses-material-design: true
  assets:
    - lib/config/immolink.env